version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: kernelkeeper/palscape:latest
    restart: unless-stopped
    ports:
      - "ip.address:8211:8211/udp" # Bind Gamerserver port to specific IP
      - "ip.address:25575:25575" # Bind RCON port to specific IP
    env_file:
      - ./default.env
    volumes:
      - ./game:/palworld