name: Build and Upload Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Docker Login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

    - name: Get short SHA
      id: slug
      run: echo "GIT_SHORT_SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

    - name: Build docker image
      run: |
        docker build . -t kernelkeeper/palscape:${{ steps.slug.outputs.GIT_SHORT_SHA7 }} -t kernelkeeper/palscape:latest

    - name: Push docker image to DockerHub
      run: |
        docker push kernelkeeper/palscape:${{ steps.slug.outputs.GIT_SHORT_SHA7 }}
        docker push kernelkeeper/palscape:latest